name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Asegúrate de que este token tenga permisos

      - name: Replace placeholder with server URL
        run: |
          sed -i 's|%%SERVER_ADDRESS%%|${{ secrets.SERVER_ADDRESS }}|g' index.template.html
          mv index.template.html index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Utilizando el token correctamente
          publish_dir: ./
